### PR TITLE
WebRT 72994: Fix for NPE in SqlQuery HAVING() clause.

### PR DESCRIPTION
**Pull request by at88mph**
Bug fix for the NPE in SQL Query.  I'm not sure why the diff reports changes to spaces.

### CODE REVIEW

**Comment by opencadc-admin** [comment]
The work-around seems wrong - indicates that some code is resetting the SelectNavigator to null so probably a SubNavigator is being reused inside two other components. I think if you changes the SubNavigator.setSelectNavigator method to do this check instead:

if (this.selectNavigator != null)
  throw new IllegalStateException("BUG: cannot reset SlectNavigator"); 

you would get a stack trace that would tell you who is trying to set it back to null. If that is in a ctor then you'll know where the SubNavigator is being illegally re-used). If it is due to the recursive use in a sub-query then it might be harder to fix. But worth a try...

**Comment by at88mph** [comment]
Here is the stack trace from the unit tests after that change:

    [junit] java.lang.IllegalStateException: BUG: cannot reset SelectNavigator
    [junit] 	at ca.nrc.cadc.tap.parser.navigator.SubNavigator.setSelectNavigator(SubNavigator.java:117)
    [junit] 	at ca.nrc.cadc.tap.parser.navigator.SelectNavigator.<init>(SelectNavigator.java:152)
    [junit] 	at ca.nrc.cadc.tap.parser.extractor.SelectListExtractor.<init>(SelectListExtractor.java:101)
    [junit] 	at ca.nrc.cadc.tap.AdqlQuery.init(AdqlQuery.java:163)
    [junit] 	at ca.nrc.cadc.tap.AdqlQuery.doNavigate(AdqlQuery.java:190)
    [junit] 	at ca.nrc.cadc.tap.AdqlQuery.getSQL(AdqlQuery.java:289)
    [junit] 	at ca.nrc.cadc.tap.parser.AdqlQueryTest.doit(AdqlQueryTest.java:170)
    [junit] 	at ca.nrc.cadc.tap.parser.AdqlQueryTest.testTopSelect(AdqlQueryTest.java:235)

**Comment by opencadc-admin** [comment]
Ah, cool. The bugs are at line 143-144 of SqlQuery and 161-162 of AdqlQuery: it is reusing two navigators instead of creating new ones... the navigator sharing is probably ok is some cases but fragile. I think this can be fixed by instantiating new instances of those two instead of re-using.

**Comment by opencadc-admin** [comment]
OH, I see another re-use of a navigator down in the TableNameConverter code that supports uploaded tables. line 160 in SqlQuery and probably the same in AdqlQuery. That could be fragile too.

**Comment by at88mph** [comment]
Thanks.  New pull request added.  I left the new check in place.

**Comment by pdowler** [comment]
Are these changes still relevant or has this been fixed in cadc-tap-server?

**Comment by pdowler** [comment]
obsolete

**Pull request closed without merging**
